### ISSUE TITLE
Gathering all works done for Milestone1 and printing to a pdf

### ISSUE THREAD

**Issue by Oozankilic** [bounswe/2021SpringGroup5#108]

**Comment by zudiay** [comment]
The RAM section is completed, available [here](https://github.com/bounswe/2021SpringGroup5/files/6447377/Cmpe352.-.RAM.pdf)

**Comment by zudiay** [comment]
The RAM section is completed, available [here](https://github.com/bounswe/2021SpringGroup5/files/6447377/Cmpe352.-.RAM.pdf)

**Comment by Oozankilic** [comment]
Report is prepared and uploaded as PDF to wiki and moodle. Wiki link of report is : [link](https://github.com/bounswe/2021SpringGroup5/blob/master/deliverables/M1-Group5.pdf)

**Comment by zudiay** [comment]
There has been an update in RAM, new version is accessible [here](https://github.com/bounswe/2021SpringGroup5/files/6448268/RAM.pdf)
