### ISSUE TITLE
Merge dailyQuote API to master

### ISSUE THREAD

**Issue by zudiay** [bounswe/2021SpringGroup5#144]
I have pushed my api in [zudiaybranch](https://github.com/bounswe/2021SpringGroup5/tree/zudiaybranch). I will merge the code if no problems are encountered.

- [x] Create pull request.
- [x] Request review from Umut
- [x] Solve issues if encountered
- [x] Merge into master

**Comment by umutgun17** [comment]
I will review your API and I will give you feedback as soon as possible

**Comment by zudiay** [comment]
Umut requested there were no issues and accepted the [pull request](https://github.com/bounswe/2021SpringGroup5/pull/143) I have created. The code was successfully merged into master.

**Comment by zudiay** [comment]
I made another commit that implies a small correction. I reopen this issue

**Comment by zudiay** [comment]
The [pull request](https://github.com/bounswe/2021SpringGroup5/pull/181) is accepted!

**Comment by umutgun17** [comment]
I tested your code and I accepted pull request. Your branch is merged perfectly.
