### ISSUE TITLE
Preparing M2 report and Submitting to Moodle

### ISSUE THREAD

**Issue by Oozankilic** [bounswe/2021SpringGroup5#164]
Tables and ingredients of M2 report will be gathered. The report pdf will be submitted to moodle

**Comment by atasoyfurkan** [comment]
I have a suggestion for preparing M2 report. You can use Notion app to prepare it. I am using it in other classes, and I think it is easy to write report with it.

**Comment by Oozankilic** [comment]
thank you @atasoyfurkan. I will try Notion

**Comment by Oozankilic** [comment]
Report PDF is prepared and added to github. The PDF can be reached here: https://github.com/bounswe/2021SpringGroup5/blob/master/deliverables/M2-Group5-updated.pdf
