### ISSUE TITLE
Complete Milestone 2 sections

### ISSUE THREAD

**Issue by zudiay** [bounswe/2021SpringGroup5#170]
I will prepare the following sections for our Milestone 2 report:

- [x] Summary of project and overall status
- [x] Evaluation of tools and processes you have used to manage your team project. This is a lessons learned from the project development decisions made so far – how effectively are the tools are being utilized & what changes (if any) are needed as you move forward?

**Comment by zudiay** [comment]
I reviewed previous year's Milestone 2 reports and our Milestone 1 report and created a draft about what I will write. I will be starting the writing process soon.

**Comment by zudiay** [comment]
I finished most of the summary and overall status. I documented all work we have done up to now. But we still have some time and work to do until we deliver the report.  So it will be fully completed at the very last day.

**Comment by zudiay** [comment]
I finished the evaluation of tools and processed part mostly. I uploaded both parts into drive and shared with group members. If they see any point I have missed, I will edit it.

**Comment by atasoyfurkan** [comment]
Hi Didem, 
I reviewed the evaluation of tools and processed part. It is well-written and includes all tools we used. Thank you for your good work! However, I used one tool different from that. I am adding it in here. Can you add to docs?

Visual Studio Code: Visual Studio Code is a code editor with a lot of capabilities which are debugging, integrated terminal, formatting code, and git interface. Also, It has wide community, and useful extensions. We used it for these reasons.

**Comment by zudiay** [comment]
Hi Furkan, Thank you for the review and the addition. I added it to our report.

**Comment by zudiay** [comment]
I believe with the addition by Furkan, evaluation of tools part is completed. I will finish the summary soon.

**Comment by zudiay** [comment]
I completed the summary section, too. I shared the google doc with the group members and I am waiting for feedbacks. If there is nothing missing, I will share it with Ozan so he would put it in our group report.

**Comment by berkaybor** [comment]
You can modify following parts in the report:

Docker: Docker is a widely used tool and we used it to containerize our application. Using docker, we packed our code into a container and isolated it. We used docker-compose to create two different services for django and for the database. We also dockerized the django application to deploy it safely and quickly.

**Comment by zudiay** [comment]
Thanks Berkay! I did the update
