### ISSUE TITLE
Review Mahmet Fatih's code

### ISSUE THREAD

**Issue by GozdeUnver** [bounswe/2021SpringGroup5#188]
I noticed that after his merge to the master, his app was not in the practice app file, there were unnecessary pycaches. I told him to do these changes and I will review them. I also asked him whether his path convention also works with the one in the master. If it doesn't, he will modify

**Comment by GozdeUnver** [comment]
He sent me this pull request but there was no valid code in Authentication app. It is not ready to merge. You can see [here](https://github.com/bounswe/2021SpringGroup5/pull/186)

**Comment by e7hdk** [comment]
Yeah true, I found bug and fixed it; I learned a lot from my mistakes :)

**Comment by berkaybor** [comment]
Fixed Fatih's folder structure and merged to master.
