### ISSUE TITLE
Meeting notes & setting up a Discord channel

### ISSUE THREAD

**Issue by GozdeUnver** [bounswe/2021SpringGroup5#2]
Conclusions of our meeting that we had on 26.04.2021 should be written down and a Discord channel for our group should be created.

**Comment by zudiay** [comment]
Meeting #1 notes can be reached here: [](https://github.com/bounswe/2021SpringGroup5.wiki.git)

**Comment by zudiay** [comment]
Meeting 1 notes can be reached here: https://github.com/bounswe/2021SpringGroup5.wiki.git
