### ISSUE TITLE
Write challenges we met as a group

### ISSUE THREAD

**Issue by cagin24** [bounswe/2021SpringGroup5#210]
I write the "challenges we met as a group" in this file: [Challenges We Met As A Group.docx](https://github.com/bounswe/2021SpringGroup5/files/6626379/Challenges.We.Met.As.A.Group.docx)

**Comment by atasoyfurkan** [comment]
You can add to docx these as well:

- It was hard to catch up on all tasks we have in Milestone 2 and also, jobs we have to do in other classes. 
- It was hard to both writing Milestone and code at the limited time (I think timing was not enough)

**Comment by cagin24** [comment]
> You can add to docx these as well:
> 
> * It was hard to catch up on all tasks we have in Milestone 2 and also, jobs we have to do in other classes.
> * It was hard to both writing Milestone and code at the limited time (I think timing was not enough)

added.

**Comment by umutgun17** [comment]
I personnelly met some challenges. 

- It's hard to find free useful API to integrate my API
- while creating branch and committing, something happened which I don't understand. Although every terminal code is correct, I cannot create branch. After reopen computer and terminal, it's fix.

**Comment by cagin24** [comment]
Added all comments and closed.
