### ISSUE TITLE
Creating Project Plan

### ISSUE THREAD

**Issue by umutgun17** [bounswe/2021SpringGroup5#215]
I will create project plan

**Comment by umutgun17** [comment]
I created title of the works and I shared them via discoard. If there is no objection, I will add times and send to Oğuz to insert it to milestone2

**Comment by atasoyfurkan** [comment]
I looked to project plan. It is looking good. It contains all main parts we did in the project. Also, periods we did tasks seems correct. Thanks for your effort.

**Comment by umutgun17** [comment]
Thank for your reviewing Furkan!

There is no objection. Therefore, it was added into Milestone 2 report!
