### ISSUE TITLE
Writing list the status of deliverables

### ISSUE THREAD

**Issue by umutgun17** [bounswe/2021SpringGroup5#216]
I will write list the status of deliverables (code documentation, API documentation, practice-app)

**Comment by umutgun17** [comment]
After TA meeting, Gözde want to take one of the status of deliverables because she want to help documentation. Therefore, she took just code documentation

**Comment by umutgun17** [comment]
I wrote API documentation and practice-app and I shared it via discoard. If there is no objection. I will send it to Ozan to add into milestone2

**Comment by atasoyfurkan** [comment]
I reviewed it now. Everything is fine with it. Thanks for your efforts!

**Comment by umutgun17** [comment]
There is not any objection. Therefore, they were added into Milestone 2 report!

**Comment by atasoyfurkan** [comment]
I found that Dockerizing API is also a deliverable, and add description for it into Milestone 2 report.
