### ISSUE TITLE
Examining related software systems

### ISSUE THREAD

**Issue by GozdeUnver** [bounswe/2021SpringGroup5#22]
@atasoyfurkan  and @Oozankilic should discover some software systems that are related to our project and create a comparison table stating the common and different aspects.

**Comment by GozdeUnver** [comment]
@Oozankilic will especially examine [sweaters app](https://www.sweatersapp.com/SweatersAppNedir)

**Comment by atasoyfurkan** [comment]
I will examine [Chember](https://chember.co/index_tr.html)

**Comment by Oozankilic** [comment]
Apps are analyzed, comparison table added to wiki
