### ISSUE TITLE
Decide Login/Log Out/Registration/Forgot pw requests

### ISSUE THREAD

**Issue by salih997** [bounswe/2021SpringGroup5#254]
We need  to decide login, log out, registration and forgot password requests. I will open a [google sheet](https://docs.google.com/spreadsheets/d/1nTP6YCbftro9izp67gA3ic5Sz3R2mvjUxVNsyxNVQIk/edit#gid=0) for these documentation.
Also we need to decide how to use activity stream functionalities.

**Comment by GozdeUnver** [comment]
We updated jsons for Login and registiration3 page.

**Comment by GozdeUnver** [comment]
after the team meeting we had, we learned that frontend will not send requests to the page redirections so we used to have 3 stage registration function but now we have only one because frontend will send the request at the end of the registration period.
