### ISSUE TITLE
Writing meeting notes 21

### ISSUE THREAD

**Issue by GozdeUnver** [bounswe/2021SpringGroup5#266]
I will take the notes of our team meeting that we have on 02.11.2021

**Comment by GozdeUnver** [comment]
I wrote down the notes and created a wiki page [here](https://github.com/bounswe/2021SpringGroup5/wiki/Meeting-%2321-Notes--02.11.2021)

**Comment by umutgun17** [comment]
Update: the meeting number is 22

I updated on the sidebar and meeting page.
