### ISSUE TITLE
Learn Git!

### ISSUE THREAD

**Issue by GozdeUnver** [bounswe/2021SpringGroup5#3]
We should have a good understanding of Git! 

- [x] @GozdeUnver 
- [x] @berkaybor 
- [x] @atasoyfurkan 
- [x] @e7hdk 
- [x] @zudiay 
- [x] @salih997 
- [x] @Oozankilic 
- [x] @umutgun17 
- [x] @cagin24 

![WhatsApp Image 2020-05-31 at 01 26 14](https://user-images.githubusercontent.com/56361766/112687349-6ec47f80-8e88-11eb-83b7-98ae72af271b.jpeg)

**Comment by atasoyfurkan** [comment]
I added the commands I learned from the video to the wiki. You can make changes on it. 
Link: [Git](https://github.com/bounswe/2021SpringGroup5/wiki/Git)

**Comment by GozdeUnver** [comment]
I added some new commands to the wiki page. #13

**Comment by GozdeUnver** [comment]
Even though this was the previous week's task, we can reopen this issue so that the team members that haven't finished studying can study this week and then we can close the issue.
