### ISSUE TITLE
Creating customer questions

### ISSUE THREAD

**Issue by GozdeUnver** [bounswe/2021SpringGroup5#32]
Everyone should find some questions to ask the customers and then we will edit our requirements according to these results. Customer questions will also be written on our Google Docs page.

**Comment by zudiay** [comment]
I have created a draft page for customer questions. Feel free to edit [here](https://github.com/bounswe/2021SpringGroup5/wiki/Customer-Questions---Draft)

**Comment by GozdeUnver** [comment]
We created the customer questions wiki [page](https://github.com/bounswe/2021SpringGroup5/wiki/Customer-Questions).
