### ISSUE TITLE
Complete Requirements

### ISSUE THREAD

**Issue by atasoyfurkan** [bounswe/2021SpringGroup5#34]
- Look to requirements and finished the missing parts

**Comment by zudiay** [comment]
You can edit it [here](https://github.com/bounswe/2021SpringGroup5/wiki/Project-Requirements---Draft).
The unfinished parts have ??? near them. Also, the page design seems very bad but i couldn't do better since there are many subsections of different depth. Please feel free to edit.

**Comment by GozdeUnver** [comment]
Section 1.1.2 of the requirements is completed
