### ISSUE TITLE
Edit Requirements according to Questions

### ISSUE THREAD

**Issue by atasoyfurkan** [bounswe/2021SpringGroup5#35]
- Look to their requirements part and will edit the necessary things after answer come to Question part from instructor

**Comment by GozdeUnver** [comment]
I updated user requirements in section 1.1.2 of the [requirements page](https://github.com/bounswe/2021SpringGroup5/wiki/Customer-Questions) according to the customer answers.

**Comment by zudiay** [comment]
I updated some system requirements, mainly authentication, sport constraints and events parts. If you have something to add/remove, feel free to edit.
