### ISSUE TITLE
Add glossary

### ISSUE THREAD

**Issue by atasoyfurkan** [bounswe/2021SpringGroup5#37]
- Everyone will add glossary from their part.

**Comment by zudiay** [comment]
I have created a draft glossary page. Feel free to edit [here](https://github.com/bounswe/2021SpringGroup5/wiki/Glossart---Draft)

**Comment by GozdeUnver** [comment]
I added the keywords that are used in section 1.1.2 of the [requirements page](https://github.com/bounswe/2021SpringGroup5/wiki/Project-Requirements)

**Comment by salih997** [comment]
I added some keywords and explanations to the glossary section. However some keywords needs to be explained for non-functional section.

**Comment by Oozankilic** [comment]
I added needed explanations on user page part

**Comment by umutgun17** [comment]
I added some explanations to the glassary section

**Comment by atasoyfurkan** [comment]
We finished glossaries in last meeting.
