### ISSUE TITLE
Resolving CORS error

### ISSUE THREAD

**Issue by GozdeUnver** [bounswe/2021SpringGroup5#416]
Frontend was receiving CORS error while sending requests to deployed backend. I will resolve this issue

**Comment by GozdeUnver** [comment]
I added CORS library to the settings so that frontend and mobile can send requests PR is [here](https://github.com/bounswe/2021SpringGroup5/pull/404)

**Comment by GozdeUnver** [comment]
I made another pull request because frontend was still receiving CORS errors. In this pull request I added CORS_ALLOW_CREDENTIALS= True and now frontend doesn't receive CORS errors anymore [here](https://github.com/bounswe/2021SpringGroup5/pull/404)

**Comment by atasoyfurkan** [comment]
I made some suggestions to the backend about how to resolve CORS errors. I suggested looking at [this link](https://pypi.org/project/django-cors-headers/) since I used it before in one of my projects.
