### ISSUE TITLE
Enter example data to deployed database

### ISSUE THREAD

**Issue by salih997** [bounswe/2021SpringGroup5#441]
We need to enter example data to demonstrate our scenerios. I will create event posts. Please add some equipment post by looking our [google sheet document](https://docs.google.com/spreadsheets/d/1nTP6YCbftro9izp67gA3ic5Sz3R2mvjUxVNsyxNVQIk/edit#gid=0)

**Comment by salih997** [comment]
I entered several event posts. Here 4 example event posts summary.

id 3
* soccer game
* address near silivri
* 25 december

id 9
* hali saha
* etiler		
* 18 december

id 7
* lets play basketball
* izmit
* 17 december

id 8
* tennis mate
* etiler
* 18 december

**Comment by salih997** [comment]
Some example search queries and returns:



|    search      |      match event id      |
|---------------------|------------------|
|'tennis'  keyword| 8 |
|'ball'  keyword| 3 9 7 (hali saha(sport type='football'), soccer, basketball) |
|'ball' keyword (sport type='football') | 3 9 |
|15-20 december | 7 8 9 |
|near etiler (with radius 3-4)|8 9|

In third search it eliminated basketball because we choose sport type football

**Comment by GozdeUnver** [comment]
I send 2 create equipment post requests

**Comment by salih997** [comment]
We entered enough example data. Maybe for milestone 3 we can reset the database and enter new values.
