### ISSUE TITLE
Preparing presentation for milestone 2 (customer presentation)

### ISSUE THREAD

**Issue by umutgun17** [bounswe/2021SpringGroup5#465]
I will do below for milestone 2 (customer presentation)

- Prepare a scenario
- Write an outline about what can be said

**Comment by umutgun17** [comment]
I communicated with other team members and the everything is okay to presentate demo

**Comment by umutgun17** [comment]
My scenario is consist of

- Profile Page
- Creating Event Post Page
- Searching Event
- Filter Event
- View Event Detail

**Comment by umutgun17** [comment]
I prepared an outline and presented it

**Comment by atasoyfurkan** [comment]
I communicated with Umut about presentation content, everything was okay.
