### ISSUE TITLE
Correct Missing Fields of Event Search Page

### ISSUE THREAD

**Issue by atasoyfurkan** [bounswe/2021SpringGroup5#566]
- Talk with @salih997 and correct missing fields of Event Search page
   - Instead of Sport Id backend should send information of sports as object
- Implement new version of the Event Search Page in the frontend

**Comment by atasoyfurkan** [comment]
Salih corrected missing fields as described and send me the correct API call also he recorded it to [google-docs](https://docs.google.com/spreadsheets/d/1nTP6YCbftro9izp67gA3ic5Sz3R2mvjUxVNsyxNVQIk/edit#gid=0)

**Comment by atasoyfurkan** [comment]
I corrected the missing fields on the event search page. Now, instead of sport id, the frontend shows sports category and sport date correctly. I pushed the changes to the search-screen branch and I opened a pull request.

**Comment by zudiay** [comment]
Hi Furkan. I reviewed your changes. I made 2 different requests, with and without filters and it works fine. I also checked the request json and validated the sent data is correct and in correct form. Thank you 👍
