### ISSUE TITLE
Implement Send Badge Functionality

### ISSUE THREAD

**Issue by atasoyfurkan** [bounswe/2021SpringGroup5#568]
- Implement the functionalities of Badge
    - Connect with backend
    - Implement Badge UI
        - A menu will be used for showing badges
        - A button will be used to open the menu 
    - Implement Badge functionalities
       - When the menu is clicked, all available badges will be shown
       - All available badges information will be fetched at the beginning of rendering from the backend
       - When a badge name is clicked, the badge will be sent to the chosen user. 
       - Check that whether event is finished or not, then show the badge button if the event is finished
- Communicate with @zudiay to learn when the participant list finishes because the badge will be added top of it.

**Comment by atasoyfurkan** [comment]
I implemented the UI of Badge. I used a menu to show badges and a button to open that menu.

**Comment by atasoyfurkan** [comment]
I implemented the functionality to fetch all badges. I communicated with @e7hdk and sent get request to the endpoint. Then, I used the list to show names of the badges.

**Comment by atasoyfurkan** [comment]
I implemented the functionality to send a badge when the name is clicked. I sent a post request to the endpoint with the user id and badge name.

**Comment by atasoyfurkan** [comment]
I implemented the functionality to check whether event time is passed or not. If it is passed, the badge buttons will not be shown.

**Comment by atasoyfurkan** [comment]
I communicated with @zudiay and I will add the badge component to participant list UI tomorrow.

**Comment by zudiay** [comment]
Hi Furkan. I created a pull request for participant listing feature [here](https://github.com/bounswe/2021SpringGroup5/pull/594). You can add the badge component there.

**Comment by atasoyfurkan** [comment]
Thank you @zudiay. I implemented the badge component as we discussed.
