### ISSUE TITLE
Implement Map functionality and UI for Create Event and Equipment Page

### ISSUE THREAD

**Issue by atasoyfurkan** [bounswe/2021SpringGroup5#570]
- Implement map functionalities and the UI to create pages
   - When a location is selected, a marker will appear and it will save the information as a state, then it will be sent to the backend in order to save the location information.
   - A modal will be implemented to open a map when someone wants to choose a location from the map.
- Communicate with @umutgun17 to learn when the create pages finish because the map will be added to top of it.

**Comment by atasoyfurkan** [comment]
- I implemented the functionality of choosing a location and saving it as a state. 
- I implemented a modal component of the map it will be shown when someone clicks to 'open map' button.

**Comment by atasoyfurkan** [comment]
I communicated with @umutgun17  and I will add the map component to search pages tomorrow.

**Comment by atasoyfurkan** [comment]
- I edit the implementation of the state changes. Now, it is compatible with what Umut wrote on Create Event Page.

**Comment by umutgun17** [comment]
Thank you @atasoyfurkan You implemented map functionlity succesfully on create event page.

**Comment by umutgun17** [comment]
I tested it and I merged your pull request.

**Comment by umutgun17** [comment]
Also, I will implement it on Equipment Post Page while using your feedbacks and modal. Thanks again.
