### ISSUE TITLE
Crete Scenarios

### ISSUE THREAD

**Issue by berkaybor** [bounswe/2021SpringGroup5#59]

**Comment by GozdeUnver** [comment]
I wrote [scenario 3](https://github.com/bounswe/2021SpringGroup5/wiki/Scenario-3-&-Mockup).

**Comment by GozdeUnver** [comment]
[Scenario 1](https://github.com/bounswe/2021SpringGroup5/wiki/Scenario-1-&-Mockup) is also done since @berkaybor and I wrote it together.

**Comment by berkaybor** [comment]
created scenario 2

**Comment by berkaybor** [comment]
Need to edit scenario 2 as only representing event creation and participant selection. Need to simplify other scenarios.

**Comment by berkaybor** [comment]
Updated scenario 2 to only represent event creation. Need to add mock-up images to scenario 2

**Comment by GozdeUnver** [comment]
I added the acceptance criteria to [scenario 4](https://github.com/bounswe/2021SpringGroup5/wiki/Scenario-4-&-Mockup)

**Comment by GozdeUnver** [comment]
Text parts of all 4 scenarios are finished.
