### ISSUE TITLE
Helping Authentication Token Issue 

### ISSUE THREAD

**Issue by atasoyfurkan** [bounswe/2021SpringGroup5#612]
- Help Didem Aytac and the backend team to resolve the bugs in the authentication part caused by the token
- [This issue](https://github.com/bounswe/2021SpringGroup5/issues/611) also points to the same problem opened by Didem Aytac

**Comment by atasoyfurkan** [comment]
- I made a meeting with the backend team to help Didem. After two hours of trying to find what caused the problem, I proposed to change the token functionalities of the backend because that one was incompatible with React.
- The backend team change the token functionalities but the problem couldn't be solved. After debugging, I proposed to change the Authentication header to Authorization which is a default name for the header.

**Comment by zudiay** [comment]
Your proposal solved the issue! We changed the code and opened the pull request.

**Comment by atasoyfurkan** [comment]
I also added the authorization token to the local storage of the browser. Therefore, a user doesn't need to log in every time he/she closes the browser.
