### ISSUE TITLE
Create mockup (search page)

### ISSUE THREAD

**Issue by salih997** [bounswe/2021SpringGroup5#62]
Search page should have feed, events and filter.

**Comment by atasoyfurkan** [comment]
I finished the android part of the search page. There are 3 screen in total. It will be available on [Scenario 3](https://github.com/bounswe/2021SpringGroup5/wiki/Scenario-3-&-Mockup)

**Comment by atasoyfurkan** [comment]
I finished the web part of the search page. It will be available on [Scenario 3](https://github.com/bounswe/2021SpringGroup5/wiki/Scenario-3-&-Mockup)

**Comment by atasoyfurkan** [comment]
<img width="720" alt="11" src="https://user-images.githubusercontent.com/46852761/115287812-5ed34f00-a159-11eb-8b3d-8c3461478221.png">

<img width="268" alt="1" src="https://user-images.githubusercontent.com/46852761/115287943-84f8ef00-a159-11eb-9f0b-e7218fa7e6a7.png">

<img width="720" alt="12" src="https://user-images.githubusercontent.com/46852761/115288454-21bb8c80-a15a-11eb-85ad-b09d14894dc8.png">

<img width="268" alt="2" src="https://user-images.githubusercontent.com/46852761/115288476-25e7aa00-a15a-11eb-9762-c192985c3f26.png">

 <img width="268" alt="Screen Shot 2021-04-19 at 21 58 45" src="https://user-images.githubusercontent.com/46852761/115288698-6cd59f80-a15a-11eb-99a3-c4404cd09028.png">

<img width="718" alt="Screen Shot 2021-04-19 at 22 00 20" src="https://user-images.githubusercontent.com/46852761/115288872-a5757900-a15a-11eb-97aa-47ce45a10dc7.png">

<img width="720" alt="12" src="https://user-images.githubusercontent.com/46852761/115289127-ecfc0500-a15a-11eb-8feb-589f423b61c6.png">
<img width="268" alt="2" src="https://user-images.githubusercontent.com/46852761/115289144-f08f8c00-a15a-11eb-8211-82b743928caf.png">


<img width="720" alt="13" src="https://user-images.githubusercontent.com/46852761/115289197-fe451180-a15a-11eb-886b-178eb34369d4.png">
<img width="268" alt="3" src="https://user-images.githubusercontent.com/46852761/115289218-01400200-a15b-11eb-9486-55cf786c302a.png">
<img width="268" alt="4" src="https://user-images.githubusercontent.com/46852761/115289226-03a25c00-a15b-11eb-994f-5a9668b29dfb.png">


<img width="720" alt="14" src="https://user-images.githubusercontent.com/46852761/115289419-351b2780-a15b-11eb-9e98-9d5e8b3f57e4.png">
<img width="268" alt="5" src="https://user-images.githubusercontent.com/46852761/115289424-364c5480-a15b-11eb-942f-69894a6a7b20.png">
