### ISSUE TITLE
Create new users, posts and follows for the final milestone demo

### ISSUE THREAD

**Issue by GozdeUnver** [bounswe/2021SpringGroup5#631]
@salih997 and I will create users, event posts and follows to use them in the demo

**Comment by salih997** [comment]
I created a user. Its username salo_bedo2

**Comment by GozdeUnver** [comment]
I created gozde_unver user and created a volleyball game for this user. I also switched to didemaytac user and made that user follow gozde_unver

**Comment by GozdeUnver** [comment]
I created 1 equipment post, 1 past event post for the didemaytac user

**Comment by GozdeUnver** [comment]
@salih997 sent an application request to one of the events of gozde_unver user. I accepted his  waiting application
