### ISSUE TITLE
Create new scenario for participant selection

### ISSUE THREAD

**Issue by zudiay** [bounswe/2021SpringGroup5#67]
We need an additional scenario showing the functionality of selecting the participants for an event. I prepared the mockups for the related pages [here](https://github.com/bounswe/2021SpringGroup5/issues/65).

**Comment by zudiay** [comment]
I created the page and filled some parts. You can see it [here](https://github.com/bounswe/2021SpringGroup5/wiki/Scenario-4)

**Comment by zudiay** [comment]
I added the Android mockups and updated the scenario

**Comment by GozdeUnver** [comment]
I added the acceptance criteria

**Comment by zudiay** [comment]
I added the Web mockups and added some web-related statements to the scenario
