### ISSUE TITLE
Create Class Diagram

### ISSUE THREAD

**Issue by atasoyfurkan** [bounswe/2021SpringGroup5#77]
Class diagram is the essential part of the project. It is important that class diagram should be finished before the others. Therefore, Deadline is 25 April, Sunday.

- Create an excel page which includes attributes and functions of the classes
- Compare excel with requirements so that every aspect of the project are included
- Create class diagram using a drawer application with information from excel

**Comment by atasoyfurkan** [comment]
We created template of the excel page with team on Thursday

**Comment by atasoyfurkan** [comment]
Kemal and I reviewed the excel page and we add new attributes and functions with help of requirements. After, we create the diagram via lucid.app and complete it according to excel page.

**Comment by atasoyfurkan** [comment]
I reviewed the diagram and made some changes on it on Saturday.

**Comment by atasoyfurkan** [comment]
Current version of the class diagram:

<img width="925" alt="Screen Shot 2021-04-25 at 00 48 43" src="https://user-images.githubusercontent.com/46852761/115973732-fe308180-a55f-11eb-9a54-239cfe52f7cc.png">

**Comment by umutgun17** [comment]
Elinize sağlık

Not: Bu şekilde herkese mail atabiliyor muyuz diye denemek istedim :)

**Comment by atasoyfurkan** [comment]
REFERENCES:
- https://www.visual-paradigm.com/guide/uml-unified-modeling-language/uml-aggregation-vs-composition/
- https://www.lucidchart.com/pages/
- http://www.herongyang.com/UML/Class-Diagram-Realization-Notation.html

**Comment by atasoyfurkan** [comment]
[Wiki - Class Diagram](https://github.com/bounswe/2021SpringGroup5/wiki/Class-Diagram)

**Comment by atasoyfurkan** [comment]
After meeting with instructor, Kemal and I updated Class Diagram

**Comment by cagin24** [comment]
After meeting with instructor, Furkan and I updated Class Diagram.

**Comment by zudiay** [comment]
-There has been some changes I stated in [this issue](https://github.com/bounswe/2021SpringGroup5/issues/81) after the meeting with the TA. Can you check if the updated class diagram covers these? @atasoyfurkan @cagin24

**Comment by atasoyfurkan** [comment]
> There has been some changes I stated in [this issue](https://github.com/bounswe/2021SpringGroup5/issues/81) after the meeting with the TA. Can you check if the updated class diagram covers these? @atasoyfurkan @cagin24

Yes, it covers.

**Comment by GozdeUnver** [comment]
I have reviewed the class diagram and stated the the things to update so that create sport event and apply to sport event sequence diagrams contain the methods that are stated in the class diagram. Furkan have made those changes on the class diagrams.
