### ISSUE TITLE
Create use case diagram

### ISSUE THREAD

**Issue by salih997** [bounswe/2021SpringGroup5#82]
Use case diagram needs to be created.

**Comment by salih997** [comment]
We (Salih, Berkay, Fatih) created the first draft of the use case diagram and I uploaded it to the [Use Case Diagram page](https://github.com/bounswe/2021SpringGroup5/wiki/Use-Case-Diagram)

![Use Case Diagram](https://user-images.githubusercontent.com/56520923/116728364-7e3a6980-a9ee-11eb-8ebc-eed2152bf763.png)

**Comment by salih997** [comment]
After the meeting with TA we redesign it. I colored and made changes on the design. It still needs to be reviewed (arrows between the pink bubbles and arrows between the yellow bubbles).

![Use Case Diagram](https://user-images.githubusercontent.com/56520923/116728615-cc4f6d00-a9ee-11eb-8ed2-9ae298edd877.png)

**Comment by berkaybor** [comment]
> After the meeting with TA we redesign it. I colored and made changes on the design. It still needs to be reviewed (arrows between the pink bubbles and arrows between the yellow bubbles).
> 
> ![Use Case Diagram](https://user-images.githubusercontent.com/56520923/116728615-cc4f6d00-a9ee-11eb-8ed2-9ae298edd877.png)

Uploaded this image that we created to wiki

**Comment by berkaybor** [comment]
Closing this since there will be no further changes to the use case diagram
